### ISSUE TITLE
有一个小问题

### ISSUE THREAD

**Issue by sztuxp** [mix-go/mix#10]
对于子命令的帮助，只支持--help 不支持 -h
myapp command1 -help
不支持
myapp command1 -h

**Comment by onanying** [comment]
@sztuxp 这个是特意为之，因为 -h 通常作为 --host 参数的简称，我不想让这个参数被占用。

**Comment by sztuxp** [comment]
好的，我建议统一，-h全部不用于帮助。谢谢你的产品，很好用！
