### ISSUE TITLE
API模式下数据库的使用

### ISSUE THREAD

**Issue by Zhu-Ying** [mix-go/mix#11]
根据文档使用Gorm的方法：
```golang
db := di.Gorm()
user := User{Name: "Jinzhu", Age: 18, Birthday: time.Now()}
result := db.Create(&user)
fmt.Println(result)
```

在Controller实现数据库查询业务时，对于`db := di.Gorm()`的使用，应该每次都`db := di.Gorm()`创建一个新的db变量，还是在某个位置声明并创建一个全局的db变量，所有controller公用这个db变量？

**Comment by onanying** [comment]
@Zhu-Ying `di.Gorm()` 返回的就是一个全局对象，你每次返回的都是同一个，是用 di 做的依赖管理，用的是 mix/xdi 库
