### ISSUE TITLE
Can you introduce the framework loading process of the following rectification projects? Because gin's default loading process, such as DB Error Logger, is for a Beans instance. These components, if a server provided by GIN is not available, how to replenish the corresponding Error message instead of the service being unavailable due to panic

### ISSUE THREAD

**Issue by sjfxy** [mix-go/mix#2]
Can you introduce the framework loading process of the following rectification projects? Because gin's default loading process, such as DB Error Logger, is for a Beans instance. These components, if a server provided by GIN is not available, how to replenish the corresponding Error message instead of the service being unavailable due to panic

**Comment by sjfxy** [comment]
Whether can be pushed through the channel for will panic up into a structure and then we can get information from this channel asynchronous because the Db main pieces of Redis components should be at the time of use in the initialization instead of in the process of loading the frame in the process of service launch led to the service itself, not with the main coroutines can active the panic different levels of distributed processing and GinServer is normal running in the background is looked at through the distributed mechanism Is it possible to do different levels of error handling in the main coroutine effectively instead of panic? Is there such a way to give an externally injected error acceptance channel ER

**Comment by onanying** [comment]
@sjfxy 骨架代码里就能了解到你问的这些信息，mix 的全部组件都是先加载的，然后在 Command 里启动的 gin ，当然代码里任何位置都能用 beans 里的组件了，然后关于修改默认的错误返回，这个 gin 自己有提供，就是通过中间件的方式，gin 官网有写，你去了解一下：https://github.com/gin-gonic/gin#using-middleware     这里的 `r.Use(gin.Recovery())` 就是，可以自己写一个中间件 Use 进去。

**Comment by sjfxy** [comment]
Beans if handle or resource is already inside must ensure that the database connection parameters initiative to initialize correctly handle means must ensure that the server database services to maintain normal rather than return I thought is a data structure or return the data like a database structure used in real time to a TCP connection



The router. Use (gin2. Recovery ()) I understand



Very well, thank you.

**Comment by sjfxy** [comment]
The router. Use (gin2. Recovery ()) I understand



Very well, thank you.
