### ISSUE TITLE
编译及运行main.go出错，安装了console,api,web

### ISSUE THREAD

**Issue by fenghoer** [mix-go/mix#4]
按照文档demo，一步步做：
https://www.kancloud.cn/onanying/mixgo1/1894807
错误信息：
```
go build -o bin/go_build_main_go.exe main.go
# hello/commands
commands\server.go:15:7: Addr redeclared in this block
        previous declaration at commands\api.go:21:14
commands\web.go:22:7: Addr redeclared in this block
        previous declaration at commands\server.go:15:14
```
提示显示可能是端口冲突，改了commands/api.go 里的端口为 8081，改commands/web.go里的端口为8082，server.go里没有动（8080）。接着跑还是报这个错误。

编辑器使用的：vscode. 安装的插件：go 0.18.1

**Comment by onanying** [comment]
正常你这种错误是：同一个目录下有多个 package main，如果没有的话，你升级一下你的 go 版本试试，你用的太老了，go mod 都不支持
