### ISSUE TITLE
`new` 生成的 cli 代码 配置文件 使用 相对目录, linux 上 无法启动.

### ISSUE THREAD

**Issue by kuchaguangjie** [mix-go/mix#47]
issue:
- 代码里 拼接了  xxx + "../xxx" 之类的 代码, 这路径在 linux 上 无法使用.
- go run main, 执行时, 临时目录在 /tmp 下某个 子目录, 即使改了路径, 只要是 相对路径, 也无法找到.

建议 修改 配置路径 拼接的 逻辑.

**Comment by onanying** [comment]
https://zhuanlan.zhihu.com/p/391857663

**Comment by kuchaguangjie** [comment]
这不能解决根本问题.
通常我都用 命令行 启动.

**Comment by onanying** [comment]
你可以注释配置文件，看起来你不想用配置文件

**Comment by onanying** [comment]
路径规则是，二进制必须在 bin 目录里面，这个是行业规则

**Comment by kuchaguangjie** [comment]
配置文件 放相对 main 的 目录 或 config/ 子目录 就可以了, 这跟 用不用 配置 没关系, 跟 可执行文件 放哪 也没关系.

**Comment by onanying** [comment]
配置文件默认就是在 conf 目录里面的，编译的二进制是要放到 bin 目录里面的，如果你按这个规则做了，那你在任何地方，不管是相对路径，还是绝对路径，执行那个二进制，他都能自己找到 conf 目录里面的配置文件。

```
.
├── README.md
├── bin
├── commands
├── conf
├── config
├── controllers
├── di
├── go.mod
├── go.sum
├── main.go
├── middleware
├── routes
└── runtime
```
