### ISSUE TITLE
怎么改写go了。。以前还用过MIXPHP呢。。

### ISSUE THREAD

**Issue by ayamzh** [mix-go/mix#8]
看来swoole是走下坡路了。。对了老大  你这有和gin fiber goframe等主流框架的性能测试对比么

**Comment by ayamzh** [comment]
我看了下 路由和httpserver是用的gin，我建议换成fiber提高不少性能可以，用法大同小异

**Comment by onanying** [comment]
@ayamzh 不是下坡路，也不是改写 go ，程序员本就会各种语言， mixgo, mixphp 的设计是跨语言通用的，也一直是计划之内的，mixphp 预计下半年更新
